### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by eladav** [Soluto/dynamico#4]
**Must haves for open sourcing the project:**
* [x] Publish a component - how do we separate the publish from retrieving the component.
* [ ] Tests...
	- [ ] client
		- [x] cli
		- [x] core
		- [ ] react
	- [x] server
		- [x] Driver
		- [x] Middleware
		- [x] fs-storage
* [x] Documentations
* [ ] Replace prettier with tslint
* [x] Publish middleware from dcmfile
* [x] Error handling in server
* [ ] Error handling in client
* [x] Error messages in Cli
* [ ] Example server

**Other cool stuff for the future:**
* [ ] Dependencies plugins for popular packages
* [ ] Think how a view manager would look like for this framework (how can we use dynamico to create a full blown micro frontends framework?)
* [ ] Optimize performance by getting default version on build time: When you build your app, dynamico pulls code for dynamic components and caches them for first time use.
* [ ] Handle offline in requests in core
* [ ] return the entire `exports` object instead of just `default` in the dynamico core
* [ ] use Auth0 free account for authentication
